apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
  labels:
    application-crd-id: kubeflow-pipelines
spec:
        #  type: NodePort
  ports:
  - name: http
    #    nodePort: 30003
    port: 9000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-service
  namespace: kubeflow
  labels:
    application-crd-id: kubeflow-pipelines
subsets:
- addresses:
  - ip: 10.0.2.227
  ports:
  - port: 9000
    name: http
    protocol: TCP
