apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - mysql-deployment.yaml
# - mysql-pv-claim.yaml
- mysql-service.yaml
- mysql-serviceaccount.yaml
- mysql-endpoint.yaml # endpint 추가 설정