apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
spec:
  type: NodePort
  ports:
  - name: minio
    nodePort: 31203
    port: 9000
    protocol: TCP
    targetPort: 9000
  # selector:
  #   app: minio
