apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui-artifact
  namespace: kubeflow-user-example-com
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "enviroment"
                    operator: "In"
                    values:
                      - "node-1"
