apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployer-deployment
  labels:
    app: cache-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-deployer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache-deployer
    spec:
      containers:
      - name: main
        image: gcr.io/ml-pipeline/cache-deployer:dummy
        imagePullPolicy: Always
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "enviroment"
                operator: "In"
                values:
                - "node-1"
      serviceAccountName: kubeflow-pipelines-cache-deployer-sa
      restartPolicy: Always
